language: ruby
rvm:
  - 2.2.2
before_install:
    - gem update --system
    - gem --version
before_script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
